variables:
  GIT_SUBMODULE_STRATEGY: recursive

windows:
  stage: build
  tags:
    - redpoint-games-windows
  script:
    - $env:GOOS="windows"; $env:GOARCH="amd64"; C:\Go\bin\go.exe build -x -o ./client.exe -ldflags -H=windowsgui ./client
  only:
    - master

# mac:
#   stage: build
#   tags:
#     - redpoint-games-mac
#   script:
#     - GOOS=darwin GOARCH=amd64 go build -x -o ./client-mac ./client
#   only:
#     - master

linux:
  stage: build
  tags:
    - redpoint-games-linux
  script:
    - GOOS=linux GOARCH=amd64 go build -x -o ./client-linux ./client
  only:
    - master