name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    
    - name: Build Windows
      run: $env:GOOS="windows"; $env:GOARCH="amd64"; go build -x -o ./JamCast-windows-amd64.exe -ldflags -H=windowsgui ./client
      shell: powershell
    
    - run: dir
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.${{ steps.buildnumber.outputs.build_number }}"
          prerelease: false
          title: "Latest"
          files: |
            *.exe
      if: github.ref == 'refs/heads/master'
